### ISSUE TITLE
Compiler error handling - syntax of actions

### ISSUE THREAD

**Issue by oritstone** [openscore/score-language#44]
Add error handling and validation to the syntax below the action proerty

**Comment by Bonczidai** [comment]
@oritstone could you give more information on this issue?
Do we want to verify that keys like python_script, java_action, className, methodName are respected?

**Comment by oritstone** [comment]
Yes.
Also that we enforce the exact syntax. 
For example. that below the *action* property there is either the *java_action* or the *python_script* property, and that below *java_action* there are always the *className* & *methodName* properties etc...

**Comment by Bonczidai** [comment]
I just committed syntax validation under java_action property (see above). This involves changes in Java_ActionTransformer class.

If we want to validate the following cases:
(1)
   - operation_action_multiple_types:
      action:
        python_script:
          print 'why am I here?'
        java_action:
          className: com.hp.thing
          methodName: someMethod (currently java_action is used in this case silently)

(2)
    - missing_action_properties:
        action:
          java_action: (fails with missing python script message)

(3)
    - missing_python_script:
        action:
          python_script:

In order to verify these cases I see two approaches:
Complex approach:
- validate in ExecutionStepFactory->createActionStep method
- in order to do that we must distinguish between the 2 cases: key is present but empty / key is not  present (currently both are interpreted as null value)
- for that I think I should modify the TransformersHandler->runTransformers method (and probably other methods / transformers - may not be a good  idea (?))

Simple approach:
- 1 is considered ok
- 2 + 3 would fail with a common message like "invalid action data" (ExecutionStepFactory->createActionStep)

WDYT?

**Comment by meirwah** [comment]
:+1: Simple approach

**Comment by oritstone** [comment]
I think that the error message should be more accurate. For example:
- If under action you something other than *python_script:* or *java_action*, you should say that only those 2 are allowed
- If under *java_action* you don't have both *className* & *methodName*, you should say which attribute is missing
- 1 above is wrong - there can't be both
