### ISSUE TITLE
 filePath must lead to a file error on existing file 

### ISSUE THREAD

**Issue by gseffy** [openscore/score-language#91]
I am getting this error message on a file that exist in the given path (report_container_metrics_cAdvisor.sl), when I rename the file to hello_word it works fine.
https://github.com/openscore/slang-content/pull/26

**Comment by meirwah** [comment]
did you try to run it with the backslash reverse ?
like this : 
C:/dev/sources/seffy-branch/org/openscore/slang/docker/maintenance/report_container_metrics_cAdvisor.sl

It seems to work.. the other way around (\) seems to be the issue..

**Comment by meirwah** [comment]
so the issue is with the "\r" chars of the flow path , which makes spring-shell to parse it the wrong way.

For a quick soultion you can use "/r" instead, and it will solve this..

we need to think on a better soultion for this (it does not seem to be solved easily, since it is a JLine issue according to @avimora ), 
or at least document this... @avimora @meshipeer @orius123 WDYT ?

**Comment by orius123** [comment]
Documenting doesn't sound like an acceptable solution in my POV. Either we fix it or we fix it..

**Comment by gseffy** [comment]
ok, it works thanks,
I suggest at least to change the error message...

**Comment by orius123** [comment]
I think that if we will verify that slashes `/` works in path for both windows and *nix, we should document to use it.

**Comment by avimora** [comment]
*nix slashes always work, and this is the recommended way...

**Comment by SamMarkowitz** [comment]
Added to the docs in openscore.github.io/3d86558a78903ca4816da7a0dfe545df54dbd6bc.

**Comment by oritstone** [comment]
pending #120 -replacing CLI FW
